# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-11 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20190408_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='democomplexresourcedata',
            name='demo1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demo_resource1', to='management.DemoResourceData'),
        ),
        migrations.AlterField(
            model_name='democomplexresourcedata',
            name='demo2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demo_resource2', to='management.DemoResourceData'),
        ),
        migrations.AlterField(
            model_name='resourcedata',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.Group'),
        ),
    ]
