# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-11 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190408_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rundata',
            name='main_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.GeneralData'),
        ),
    ]
